### ISSUE TITLE
Enable Travis for the FHIR Repository

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#13]
Enable Travis for the `FHIR` Repository

Create .travis.yml
```
###############################################################################
# (C) Copyright IBM Corp. 2019
#
# SPDX-License-Identifier: Apache-2.0
###############################################################################

# Notes: 
# SKIPPING BUILD via Travis: 
# To skip the build use: 
# [skip <KEYWORD>]
# ci, travis, travis ci, travis-ci, or travisci
# Example: [skip travis] Update README

dist: xenial
sudo: false

language: java

# use Open JDK 8
jdk:
  - openjdk8

install:
  - java -version

matrix: 
  fast_finish: true

# Using a depth of false, we don't really modify git. 
git:
  depth: false
  quiet: true
  submodules: false

before_install: 
  - echo "MAVEN_OPTS='-Xmx2G -Xms1G -XX:MaxPermSize=512m -Djava.awt.headless=true -B'" > ~/.mavenrc

# Generate the VERSION - TRAVIS_BUILD_ID
# fhir-parent-it = Integration test
script: 
  - env
  - df
  - ulimit -a
  # fhir-tools - installs the generator
  - "mvn -f fhir-tools/pom.xml -B -P jenkins clean install -Dmaven.javadoc.skip=true"
  # fhir-examples = Exampes Data
  - "mvn -f fhir-examples/pom.xml -B -P jenkins clean install -Dmaven.javadoc.skip=true"
  # fhir-parent-ut = Unit Test
  - "mvn  -f fhir-parent/pom.xml -B -P jenkins clean install -Dcom.ibm.watsonhealth.fhir.model.spec.test.R4ExamplesDriver.testType=MINIMAL"

# cache the build files
cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    recipients:
      - pbastide@us.ibm.com, lmsurpre@us.ibm.com
    on_success: never # default: change
    on_failure: always # default: always  

```

Update ci/license/issuemanagement

<version>

Uses tag-release on push tag

    Changes the mvn version (does the modification on the tag)

Travis.txt

    ci for push build

    ci for pr build

    ci for tag build and release

Protect Branches

Update travis / bintray

we could do something like this...
git log <PRIOR_TAG>...<CURRENT_TAG> --name-only - if files changed since prior, then build the project, and release only the files which match the name changes
