### ISSUE TITLE
Unable to import bulk data from Minio

### ISSUE THREAD

**Issue by tevariou** [IBM/FHIR#1854]
**Describe the bug**
I'm running the Fhir IBM server and Minio in Docker and I am unable to import a `ndjson` file from Minio to the server. It works fine importing from a static file server via `https`.

**docker-compose.yml**
```
version: "3"
services:

  fhir-api:
    image: ibmcom/ibm-fhir-server:4.5.3
    restart: on-failure
    volumes:
      - ./server.xml:/opt/ol/wlp/usr/servers/fhir-server/configDropins/overrides/server.xml
      - ./fhir-server-config.json:/opt/ol/wlp/usr/servers/fhir-server/config/default/fhir-server-config.json
    ports:
      - 9443:9443
      - 9080:9080
    environment:
      JDK_JAVA_OPTIONS: -Xmx4g

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=fhirserver
      - POSTGRES_PASSWORD=change-password
      - POSTGRES_DB=fhirdb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    privileged: true
    volumes:
      - ./miniodata:/data1
      - ./certs:/root/.minio/certs
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: change-password
      MINIO_HTTP_TRACE: /dev/stdout
    command: server /data1

volumes:
  pgdata:
```

**fhir-server-config.json**
```
{
    "__comment": "FHIR Server configuration",
    "fhirServer": {
        "core": {
            "tenantIdHeaderName": "X-FHIR-TENANT-ID",
            "datastoreIdHeaderName": "X-FHIR-DSID",
            "checkReferenceTypes": true,
            "conditionalDeleteMaxNumber": 10,
            "disabledOperations": ""
        },
        "bulkdata": {
            "bulkDataBatchJobIdEncryptionKey": "change-password",
            "applicationName": "fhir-bulkimportexport-webapp",
            "moduleName": "fhir-bulkimportexport.war",
            "jobParameters": {
                "cos.bucket.name": "fhirbulkdata",
                "cos.location": "us",
                "cos.endpoint.internal": "https://minio:9000",
                "cos.endpoint.external": "https://minio:9000",
                "cos.credential.ibm": "N",
                "cos.api.key": "minio",
                "cos.srvinst.id": "change-password"
            },
            "implementation_type": "cos",
            "batch-uri": "https://localhost:9443/ibm/api/batch/jobinstances",
            "batch-user": "fhiradmin",
            "batch-user-password": "change-password",
            "batch-truststore": "resources/security/fhirTrustStore.p12",
            "batch-truststore-password": "change-password",
            "isExportPublic": true,
            "cosFileMaxResources": 200000,
            "cosFileMaxSize": 209715200,
            "validBaseUrls": [
                "https://minio:9000"
            ],
            "useFhirServerTrustStore": true,
            "enableParquet": false
        },
        "security": {
            "cors": true,
            "basic": {
                "enabled": true
            },
            "certificates": {
                "enabled": true
            },
            "oauth": {
                "enabled": false,
                "regUrl": "https://<host>:9443/oauth2/endpoint/oauth2-provider/registration",
                "authUrl": "https://<host>:9443/oauth2/endpoint/oauth2-provider/authorize",
                "tokenUrl": "https://<host>:9443/oauth2/endpoint/oauth2-provider/token",
                "smart": {
                    "enabled": false,
                    "scopes": ["openid", "profile", "fhirUser", "launch/patient", "patient/*.*", "offline_access"],
                    "capabilities": [
                        "sso-openid-connect",
                        "launch-standalone", 
                        "client-public", 
                        "client-confidential-symmetric", 
                        "permission-offline",
                        "context-standalone-patient",
                        "permission-patient"
                    ]
                }
            }
        },
        "audit": {
            "serviceClassName" : "com.ibm.fhir.audit.impl.NopService"
        },
        "persistence": {
            "factoryClassname": "com.ibm.fhir.persistence.jdbc.FHIRPersistenceJDBCFactory",
            "common": {
                "__comment": "Configuration properties common to all persistence layer implementations",
                "updateCreateEnabled": true
            },
            "jdbc": {
                "__comment": "Configuration properties for the JDBC persistence implementation",
                "bootstrapDb": true,
                "enableProxyDatasource": false,
                "bootstrapDataSourceBase": "jdbc/bootstrap",
                "enableCodeSystemsCache": true,
                "enableParameterNamesCache": true,
                "enableResourceTypesCache": true
            },
            "datasources": {
                "default": {
                    "type": "postgresql",
                    "currentSchema": "fhirdata"
                }
            }
        }
    }
}
```

** Steps to reproduce **

Here the request to the fhir server to run the import job:
```
curl -k -v -u "fhiruser:change-password" -H 'Content-Type: application/fhir+json' 'https://localhost:9443/fhir-server/api/v4/$import' -d '{
    "resourceType": "Parameters",
    "id": "30321130-5032-49fb-be54-9b8b82b2445a",
    "parameter": [
        {
            "name": "inputFormat",
            "valueString": "application/fhir+ndjson"
        },
        {
            "name": "inputSource",
            "valueUri": "https://localhost:9443/source-fhir-server"
        },
        {
            "name": "input",
            "part": [
                {
                    "name": "type",
                    "valueString": "Patient"
                },
                {
                    "name": "url",
                    "valueUrl": "https://minio:9000/fhirbulkdata/test-import.ndjson"
                }
            ]
        },
        {
            "name": "storageDetail",
            "valueString": "aws-s3"
        }
    ]
}'
```
And here the resulting bulkdata status:
```
<OperationOutcome xmlns="http://hl7.org/fhir">
<id value="ac-16-0-4-56569032-b6ee-4477-a9ca-5bf2b7caa455"/>
<issue>
<severity value="error"/>
<code value="transient"/>
<diagnostics value="An unexpected error has ocurred while checking the status"/>
</issue>
</OperationOutcome>
```
The docker logs don't show any error otherwise.

**Expected behavior**
* The error output may be more explicit 
* Bulkdata status should return something
